sudo: required
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
    - CLOUDSDK_PYTHON=python3.8 # Set Google Cloud SDK to use Python 3.8
before_install:
  # Add deadsnakes PPA and install Python 3.8
  - sudo add-apt-repository ppa:deadsnakes/ppa -y
  - sudo apt-get update
  - sudo apt-get install -y python3.8
  - sudo update-alternatives --install /usr/bin/python python /usr/bin/python3.8 1

  # Decrypt service account credentials
  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d

  # Install Google Cloud SDK
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc

  # Update and configure gcloud components
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json
  - gcloud config set project multi-k8s-439616
  - gcloud config set compute/zone europe-west3-a
  - gcloud container clusters get-credentials multi-cluster

  # Docker login and build
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t serhiidocker/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true serhiidocker/react-test npm test

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: main
